name: Build and Release C++ Optimizer

on:
  push:
    branches: [ "main" ]
    # İŞTE DÜZELTİLEN KISIM BURASI: tags artık push'un tam altında!
    tags:
      - 'v*' 
  workflow_dispatch: 

permissions:
  contents: write 

jobs:
  build-and-release:
    runs-on: windows-latest 

    steps:
    - name: Depoyu Klonla (Checkout)
      uses: actions/checkout@v4

    - name: C++ Kodunu Derle (Sifir Bagimlilik - Mutlak Statik)
      shell: cmd 
      run: |
        g++ main.cpp -o QruxNetworkOptimizer.exe -O3 -s -DNDEBUG -static -static-libgcc -static-libstdc++ -Wl,-Bstatic -lpthread -Wl,-Bdynamic

    - name: Derlenen Exe Dosyasini Gecici Olarak Yayinla
      uses: actions/upload-artifact@v4
      with:
        name: QruxNetworkOptimizer-Release
        path: QruxNetworkOptimizer.exe
        if-no-files-found: error

    - name: GitHub Release Olustur ve Exe Dosyasini Yukle
      if: startsWith(github.ref, 'refs/tags/') 
      uses: softprops/action-gh-release@v2
      with:
        files: QruxNetworkOptimizer.exe
        generate_release_notes: true 
